---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/boreBoar/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - aircrack-ng
  - bettercap
  - go
  - helm
  - libmagic
  - neovim
  - node
  - ncurses
  - pyenv
  - pyenv-virtualenv
  - jq
  - tmux
  - rke
  - terraform@0.12
  - tree
  - htop
  - kakoune
  - tldr
  - wget
  - nmap
  - bash-completion
  - watch
  - icu4c
  - python@3.9
  - gettext
  - readline
  - xz
  - git
  - cmake
  - imagemagick
  - gcc
  - automake
  - coreutils
  - findutils

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - jetbrains-toolbox
  - docker
  - dropbox
  - brave-browser
  - noxappplayer
  - purevpn
  - google-cloud-sdk
  - slack
  - android-file-transfer
  - evernote
  - steam
  - sublime-text
  - the-unarchiver
  - vlc
  - iterm2
  - shift
  - authy
  - discord
  - flux

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
