---
# https://medium.com/@shivam1/make-your-terminal-beautiful-and-fast-with-zsh-shell-and-powerlevel10k-6484461c6efb
- name: Installing Zsh and git
  apt: pkg=zsh,git state=latest
  register: installation
  become: true

- name: Check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: stat_rc_result

- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists

#- name: Creating new ~/.zshrc
#  copy:
#    src=~/.oh-my-zsh/templates/zshrc.zsh-template
#    dest=~/.zshrc
#  when: not stat_rc_result.stat.exists

- name: Cloning  powerlevel10k
  git:
    repo=https://github.com/romkatv/powerlevel10k.git
    dest=~/.oh-my-zsh/custom/themes/powerlevel10k
  when: not stat_oh_my_zsh_result.stat.exists

- name: Cloning  zsh-autosuggestions
  git:
    repo=https://github.com/zsh-users/zsh-autosuggestions.git
    dest=~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  when: not stat_oh_my_zsh_result.stat.exists

- name: Cloning  zsh-syntax-highlighting
  git:
    repo=https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest=~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  when: not stat_oh_my_zsh_result.stat.exists

